// export const DOMAIN_KEY = "domain.selected"
// export const SCENARIO_KEY = "scenario.selected"
// export const MODULO_KEY = "modulo.selected"
// export const FRAGMENT_KEY = "fragment.selected"
// export const COMPOSED_ACTIVITY_KEY = "composedActivity.select"
// export const ACTIVITY_KEY = "activity.select"

export const DOMAIN_URL_PARAM = "domainId"
export const SCENARIO_URL_PARAM = "learningScenarioId"
export const MODULO_URL_PARAM = "learningModuleId"
export const FRAGMENT_URL_PARAM = "learningFragmentId"
export const COMPOSED_ACTIVITY_URL_PARAM = "composedActivityId"
export const ACTIVITY_URL_PARAM = "activityId"
