export const DOMAIN_KEY = "domain.selected"
export const SCENARIO_KEY = "scenario.selected"
export const MODULO_KEY = "modulo.selected"
export const FRAGMENT_KEY = "fragment.selected"
export const COMPOSED_ACTIVITY_KEY = "composedActivity.select"
export const ACTIVITY_KEY = "activity.select"